import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend } from "next/font/google";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { SidebarProvider } from "@/contexts/SidebarContext";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { ToastProvider } from "@/components/ui/toaster";
import { PageTransition, ViewTransition } from "@/components/ui/page-transition";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexend.variable} font-sans antialiased`}
      >
        <ErrorBoundary>
          <SidebarProvider>
            <LanguageProvider>
              <ToastProvider>
                <ViewTransition mode="wait">
                  <PageTransition>
                    {children}
                  </PageTransition>
                </ViewTransition>
              </ToastProvider>
            </LanguageProvider>
          </SidebarProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
